### ISSUE TITLE
Create a framework for reading in cell metadata and acting on it.

### ISSUE THREAD

**Issue by adpatter** [educational-technology-collective/etc_jupyterlab_cell_properties#1]
This is an example of what may be in cell metadata:

```
{
    "tags": [
        "style-extension.style1"
    ],
    "namespace is the name of the extension": {
        "style": {
            "background": "#aaa",
            "border": "1px solid black"
        },
        "permissions": {
            "user": "wrx",
            "group": "rx",
            "world": "r"
        }
    }
}
```

We want to be able to, for example, define cell types that have specific characteristics e.g., an "autograder" cell.

**Comment by adpatter** [comment]
@cab938 I have just started working on this.  For this project do we want to implement just the ability to style a cell and to set permissions on a cell?  I'm confused about what the permissions actually mean.

**Comment by adpatter** [comment]
@cab938 JupyterLab has a built-in "editable" boolean property that can be specified in the cell metadata.  You can see where this being accessed here:  https://github.com/jupyterlab/jupyterlab/blob/master/packages/cells/src/widget.ts#L329

However, I haven't been able to find anything with regard to "read" and "execute".  Also, it's not clear to me what a "user": "r" setting would do.  And, how do we differentiate between groups and users and the world?

Anyhow, I think it's note clear to me what exactly we want to do here.

**Comment by adpatter** [comment]
I am going to concentrate on the cell styling.  I'll get the part working where styles can be applied to cells by means of the metadata.

**Comment by cab938** [comment]
I think it is ok to focus on just being able to set the cell to read only, ignore write/execute or anything about groups at the moment
For that we would need a multiuser system anyways.

**Comment by adpatter** [comment]
@cab938 Setting the cell to read only is built-in.  We just need to set the key `editable` to false and the cell becomes read only.

As such, I will just focus on getting the cell styling feature working.

The idea here is for there be a means to add CSS in the cell metadata e.g., 
{
  etc-jupyterlab-cell-properties: { syle: {"background":"blue"}}
}

**Comment by adpatter** [comment]
@cab938 Please let me know if this functionality makes sense.  Here we can set the "style" property to a JavaScript CSS object and it styles the cell accordingly.  Here it is styling the "cell container".  How would you like to distinguish which part of the cell gets styled?  In other words, how do you think we should distinguish between styling the cell container and the cell itself.  Would it be too complicated to specify a class name i.e., the class name that is applied to the cell and its container in the DOM?

![image](https://user-images.githubusercontent.com/77470591/118867922-9b59ae00-b8b1-11eb-99a5-ff4899de080d.png)

**Comment by adpatter** [comment]
@cab938 For example, instead of property name being "style", it could be the class name that is applied to the relevant part of the DOM - but it would be assumed that it is a class name that is the cell or one of its children.

**Comment by cab938** [comment]
I think this is good for now! I'll have some more thoughts I think...

**Comment by adpatter** [comment]
I think this one is done for the most part.  It will handle adding and splitting cells.  It seems to handle all the cases I could think of testing.

The documentation is reasonably good.  Please let me know if anything else needs to be done on this one. @cab938
